# Generated by Django 4.1 on 2022-08-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='career',
        ),
        migrations.AddField(
            model_name='home',
            name='careers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='jobs',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team_members',
            name='members_image',
            field=models.ImageField(upload_to='members/'),
        ),
    ]
