# Generated by Django 4.1 on 2022-08-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_home_career_home_careers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill_1_name',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_2_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_3_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_4_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_5_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_6_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
