# Generated by Django 4.1 on 2022-08-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_name_skill_skill_1_name_skill_skill_2_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
