# Generated by Django 4.1 on 2022-08-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_services_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
