# Generated by Django 4.1 on 2022-08-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_projects_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_1_description',
            new_name='service_description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_1_name',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_1_price',
            new_name='service_price',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_1_name',
            new_name='skill_name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_2_description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_2_name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_2_price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_3_description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_3_name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_3_price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_4_description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_4_name',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_4_price',
        ),
        migrations.RemoveField(
            model_name='services',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_2_name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_3_name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_4_name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_5_name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_6_name',
        ),
    ]
