# Generated by Django 4.1 on 2022-08-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_service_description_services_service_1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
