# Generated by Django 4.1 on 2022-08-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_services_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='job',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team_members',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
