# Generated by Django 4.1 on 2022-09-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_contact_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('From', models.DateTimeField()),
                ('To', models.DateTimeField()),
                ('school', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=100)),
                ('From', models.DateTimeField()),
                ('To', models.DateTimeField()),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='team_members',
            name='members_link',
            field=models.URLField(blank=True),
        ),
    ]
