# Generated by Django 4.1 on 2022-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_education_experience_alter_team_members_members_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='From',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='To',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='From',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='To',
            field=models.DateField(),
        ),
    ]
