# Generated by Django 4.1 on 2022-09-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_education_from_alter_education_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=100),
        ),
    ]
