# Generated by Django 4.1 on 2022-09-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_alter_education_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='careers',
            new_name='Top_3_skills',
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=50),
        ),
    ]
