# Generated by Django 4.1 on 2022-09-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_rename_careers_home_top_3_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
