# Generated by Django 4.1 on 2022-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_form_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='message',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='subject',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
